import React from "react";
import Layout from "../layout";
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";

const Contact = () => {
  return (
    <Layout>
      <Head>
        <title>Msc jobs employers </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="h-screen bg-[#008BF3] py-[70px]">
        <div className="w-[800px] h-auto mx-auto bg-[#1F5050] py-[30px]">
          <div className="m-4 border-b-2 border-gray-700">
            <Link href="/">
              <a className="flex flex-col items-center px-16 py-8">
                <img src="/msc-logo.svg" className="h-[100px]" alt="msc-logo" />
                <div className="pt-1 text-white font-Rochester text-tiny md:pt-0 md:text-[10px]">
                  Better Career
                </div>
              </a>
            </Link>
          </div>

          <div className="flex flex-col mx-[150px] my-4">
            <div className="py-5 text-xl font-bold text-center text-white">
              CONTACT US
            </div>
            <div className="flex flex-col gap-5 pl-2 text-white sm:pl-0">
              <div className="flex flex-row">
                <div className="w-11">
                  <Image src="/placemarker.png" width={35} height={35} />
                </div>

                <div className="w-2/3 pl-3 text-sm">
                  <div className="font-bold">Maa Saraswati Consultancy</div>
                  <div> G-231, Third Floor, Techno Garden, Banglore</div>
                  <div> kharnataka- 751019</div>
                </div>
              </div>
              <div className="flex flex-row">
                <div className="w-11">
                  <Image src="/phone.png" width={30} height={30} />
                </div>

                <div className="w-auto pl-3 text-sm sm:w-3/4">
                  <div>Phone: </div>
                  <a href="tel:6370324756">7004237947</a>
                  <a href="tel:6371809622">, 8102457542</a>
                </div>
              </div>
              <div className="flex flex-row">
                <div className="w-11">
                  <Image src="/mail.png" width={30} height={20} />
                </div>

                <div className="w-auto pl-3 text-sm sm:w-3/4">
                  <a href="mailto:www.themiracletutorial@gmail.com">
                    Email: www.mscjobs@gmail.com{" "}
                  </a>
                </div>
              </div>
              <div>
                <Link href="www.facebook.com">
                  <img
                    src="/white-facebook-logo.svg"
                    alt="facebook"
                    className="inline mr-2 w-7 h-7"
                  />
                </Link>
                <Link href="www.twitter.com">
                  <img
                    src="/white-twitter-logo.svg"
                    alt="twitter"
                    className="inline mx-2 w-7 h-7"
                  />
                </Link>
                <Link href="www.linkedin.com">
                  <img
                    src="/white-linkedin-logo.svg"
                    alt="linkedin"
                    className="inline mx-2 w-7 h-7"
                  />
                </Link>
              </div>
            </div>
          </div>
        </div>
      </div>
    </Layout>
  );
};

export default Contact;
