import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Layout from "../layout";
import Link from "next/link";

export default function Home() {
  return (
    <Layout>
      <Head>
        <title>Msc jobs employers </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="h-screen bg-[#008BF3] py-[70px]">
        <div className="w-[800px] h-auto flex flex-row mx-auto bg-[#1F5050]">
          <div className="m-4 border-r-2 border-gray-700">
            <Link href="/">
              <a className="flex flex-col items-center px-16 py-8">
                <img src="/msc-logo.svg" className="h-[100px]" alt="msc-logo" />
                <div className="pt-1 text-white font-Rochester text-tiny md:pt-0 md:text-[10px]">
                  Better Career
                </div>
              </a>
            </Link>
          </div>
          <div className="m-4 mx-[130px] text-center grow">
            <div className="">
              <div className="text-xl font-bold text-white">
                Register Your Organisation
              </div>
              <div>
                <input
                  name="NameOfOrg"
                  type="text"
                  placeholder="Name of Organisation"
                  className="w-full h-6 px-3 my-1 text-sm border border-black mt-7"
                />
              </div>
              <div>
                <input
                  name="Location"
                  type="text"
                  placeholder="Location"
                  className="w-full h-6 px-3 my-1 text-sm border border-black"
                />
              </div>
              <div>
                <input
                  name="ContactNo"
                  type="text"
                  placeholder="Contact No."
                  className="w-full h-6 px-3 my-1 text-sm border border-black"
                />
              </div>
              <div>
                <input
                  name="Email"
                  type="text"
                  placeholder="Email Id"
                  className="w-full h-6 px-3 my-1 text-sm border border-black"
                />
              </div>
              <div>
                <textarea
                  name="about"
                  type="text"
                  placeholder="About"
                  className="w-full h-[100px] px-3 py-1 my-1 border text-sm border-black"
                />
              </div>
              <div>
                <input
                  type="submit"
                  className="px-4 py-1 text-white bg-red-700 cursor-pointer rounded-xl"
                  value="Submit"
                />
              </div>
            </div>

            <hr className="my-3 border-t-2 border-black" />
            <div className="mx-[30px]">
              <div className="text-xl font-bold text-white">Login</div>
              <div>
                <input
                  name="Email Id"
                  type="text"
                  placeholder="Email Id"
                  className="w-full h-6 px-3 my-1 text-sm border border-black"
                />
              </div>
              <div>
                <input
                  name="Password"
                  type="password"
                  placeholder="Password"
                  className="w-full h-6 px-3 my-1 text-sm border border-black"
                />
              </div>
              <div>
                <input
                  type="submit"
                  className="px-4 py-1 my-3 text-white bg-red-700 cursor-pointer rounded-xl"
                  value="Submit"
                />
              </div>
            </div>
          </div>
        </div>
      </div>
    </Layout>
  );
}
