import React from "react";
import Layout from "../layout";
import Head from "next/head";
import Link from "next/link";

const IndividualNotice = () => {
  return (
    <div className="px-3 py-2">
      <span className="text-gray-300">
        This is a notice, I do talk about it a lot of times, But it is not an
        ideal topic of converstation to talk about. You need to talk to your
        seniors about this issue that has just arrived.
      </span>
      <span className="inline text-xs text-green-300">
        {" {25 - Aug - 2022} "}
      </span>
      <span className="inline text-xs text-red-600">New</span>
    </div>
  );
};

const notice = () => {
  return (
    <Layout>
      <Head>
        <title>Msc jobs employers </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="h-screen bg-[#008BF3] py-[70px]">
        <div className="w-[800px] h-auto mx-auto bg-[#1F5050] py-[30px]">
          <div className="m-4 border-b-2 border-gray-700">
            <Link href="/">
              <a className="flex flex-col items-center px-16 py-8">
                <img src="/msc-logo.svg" className="h-[100px]" alt="msc-logo" />
                <div className="pt-1 text-white font-Rochester text-tiny md:pt-0 md:text-[10px]">
                  Better Career
                </div>
              </a>
            </Link>
          </div>

          <div className="flex flex-col mx-[150px] my-4">
            <div className="py-5 text-2xl font-bold text-center text-white">
              Notice
            </div>
            <div className="h-[250px] overflow-auto">
              <IndividualNotice />
              <IndividualNotice />
              <IndividualNotice />
              <IndividualNotice />
              <IndividualNotice />
              <IndividualNotice />
              <IndividualNotice />
              <IndividualNotice />
              <IndividualNotice />
              <IndividualNotice />
            </div>
          </div>
        </div>
      </div>
    </Layout>
  );
};

export default notice;
