import React from "react";
import Layout from "../layout";
import Head from "next/head";
import Link from "next/link";

const PostJob = () => {
  return (
    <Layout>
      <Head>
        <title>Msc jobs employers </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="h-auto pt-[30px] pb-[70px]">
        <div className="w-[600px] h-auto mx-auto py-[30px]">
          <div className="text-3xl pb-[30px] font-bold text-center text-red-600">
            POST JOB
          </div>
          <form>
            <div className="px-4 py-1 mx-auto">
              <div className="text-lg font-medium">
                Institute/Organisation Name
              </div>
              <input
                name="instituteName"
                type="text"
                placeholder="Institute/Organisation Name"
                className="w-full h-8 p-3 my-1 text-sm border border-black rounded"
              />
            </div>
            <div className="px-4 py-1 mx-auto">
              <div className="text-lg font-medium">Job Post</div>
              <input
                name="jobPost"
                type="text"
                placeholder="Job Post"
                className="w-full h-8 p-3 my-1 text-sm border border-black rounded"
              />
            </div>
            <div className="px-4 py-1 mx-auto">
              <div className="text-lg font-medium">Work Experience</div>
              <input
                name="workExperience"
                type="text"
                placeholder="Work Experience"
                className="w-full h-8 p-3 my-1 text-sm border border-black rounded"
              />
            </div>
            <div className="px-4 py-1 mx-auto">
              <div className="text-lg font-medium">Job Type</div>
              <input
                name="jobType"
                type="text"
                placeholder="Job Type"
                className="w-full h-8 p-3 my-1 text-sm border border-black rounded"
              />
            </div>
            <div className="px-4 py-1 mx-auto">
              <div className="text-lg font-medium">Work Location</div>
              <input
                name="workLocation"
                type="text"
                placeholder="Work Location"
                className="w-full h-8 p-3 my-1 text-sm border border-black rounded"
              />
            </div>
            <div className="px-4 py-1 mx-auto">
              <div className="text-lg font-medium">Job Description</div>
              <textarea
                name="jobDescription"
                type="text"
                placeholder="Job Description"
                className="w-full h-[100px] p-3 my-1 text-sm border border-black rounded"
              />
            </div>
            <div className="px-4 py-1 mx-auto">
              <div className="text-lg font-medium">Attachments </div>
              <input
                name="Attachment"
                type="file"
                className="w-full p-1 my-1 text-sm border border-black rounded"
              />
            </div>

            <div className="px-4 py-1 mx-auto">
              <div className="w-[30%] mx-auto ">
                <input
                  name="Submit"
                  type="submit"
                  value="Submit"
                  className="w-full p-1 my-1 text-lg bg-blue-300 border border-black rounded"
                />
              </div>
            </div>
          </form>
        </div>
      </div>
    </Layout>
  );
};

export default PostJob;
