import React from "react";
import Layout from "../layout";
import Head from "next/head";
import Link from "next/link";

const Profile = () => {
  return (
    <Layout>
      <Head>
        <title>Msc jobs employers </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="h-screen bg-[#008BF3] py-[70px]">
        <div className="w-[800px] h-auto mx-auto bg-[#1F5050] py-[30px]">
          <div className="m-4 border-b-2 border-gray-700">
            <Link href="/">
              <a className="flex flex-col items-center px-16 py-8">
                <img src="/msc-logo.svg" className="h-[100px]" alt="msc-logo" />
                <div className="pt-1 text-white font-Rochester text-tiny md:pt-0 md:text-[10px]">
                  Better Career
                </div>
              </a>
            </Link>
          </div>

          <div className="text-xl text-center text-white">
            Name of Institute
          </div>
          <div className="flex flex-row py-3 text-white mx-[100px]">
            <div className="w-[200px]">
              <div className="text-right">Member Id : </div>
              <div className="text-right">Founder : </div>
              <div className="text-right">Registered Mail Id : </div>
              <div className="text-right">Contact Number : </div>
              <div className="text-right">About Us : </div>
            </div>
            <div className="grow">
              <div>XXXXXXX</div>
              <div>Name of Founder/ Franchies Name</div>
              <div>xyz@gmail.com</div>
              <div>XXXXXXXXXX / XXXXXXXXXX</div>
              <div>This is an institute for college teachers searching</div>
            </div>
          </div>

          <div className="px-3 py-1 rounded-xl text-white w-[200px] mx-auto text-center bg-red-800">
            Edit Profile
          </div>
        </div>
      </div>
    </Layout>
  );
};

export default Profile;
